# Dependencies
markdown:         kramdown
highlighter:      rouge

# Permalinks
permalink:        pretty

# Setup
title:            Lance Batson
tagline:          "Software Development"
description:      "I'm a developer with an interest in web, mobile, desktop... really any type of software."
url:              https://lance.batson.us
baseurl:          ""

author:
  name:           "Lance Batson"
  url:            https://lance.batson.us

paginate:         5

# Custom vars
version:          3.8.5

github:
  repo:           https://github.com/poole/hyde

plugins:          [jekyll-paginate]

links:
  github:         https://github.com/lbatson
  stackoverflow:  http://stackoverflow.com/users/1415348/lbatson
  linkedin:       https://www.linkedin.com/pub/lance-batson/55/467/758
  email:          lancebatsondev@gmail.com
