# Dependencies
markdown:         kramdown
highlighter:      rouge

# Permalinks
permalink:        pretty

# Setup
title:            Lance Batson
tagline:          "Software Development"
description:      "I'm a developer with an interest in web, mobile, desktop... really any type of software."
url:              http://lancebatson.me
baseurl:          /

author:
  name:           "Lance Batson"
  url:            http://lancebatson.me

paginate:         5

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/poole/hyde

gems:             [jekyll-paginate]

links:
  github:         https://github.com/lbatson
  stackoverflow:  http://stackoverflow.com/users/1415348/lbatson
  linkedin:       https://www.linkedin.com/pub/lance-batson/55/467/758
  email:          lancebatsondev@gmail.com
